### ISSUE TITLE
Able to be run over by cars in trader safe zone 

### ISSUE THREAD

**Issue by EvanSimonson** [chrisnic/getwrecked-dev#97]
two people were able to get a bike into the safe zone and run me over.

**Comment by chrisnic** [comment]
Sorry about that. There's a way of using the race system to abuse some of the safe zone mechanics, didn't quite get around to adding something to prevent this in the last patch however.

**Comment by EvanSimonson** [comment]
Is there a plan to add a fix in the next patch?

**Comment by chrisnic** [comment]
Added a check in the race editor to prevent checkpoints being placed near the workshop. While in a race you must also remain 1km away from the workshop or an Out Of Zone warning will trigger.
